### ISSUE TITLE
安装后编译成功, 但是页面上访问不了?

### ISSUE THREAD

**Issue by aaawhz** [sunhaikuo/vue-ssr-3#1]
cnpm i => npm run dev;
http://localhost:5000/
无法访问网站?

**Comment by aaawhz** [comment]
忘了, 还有开个窗口. node server.js....

**Comment by sunhaikuo** [comment]
正解!

**Comment by aaawhz** [comment]
`const app = new Vue({ ...App,
    store
})

export default function (context) {
    return new Promise((resolve, reject) => {
        Vue.axios.get('http://localhost:5000/data').then((response) => {
            // 获取数据
            const list = response.data.data.liveWodList
            // 把数据存到Vuex里面
            store.commit(LIST.GET_DATA, list)
            // 把state存放到context中
            context.state = store.state
            resolve(app)
        })
        // context.state = store.state
        // resolve(app)
    });
};

`

resolve(app)是啥意思
